import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedEllipse23Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedEllipse20Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedEllipse22Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedScreenshot_20220403_173455removebgpreview1Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedEllipse18Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedEllipse21Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedBuyRentadvancedequipmentrequirementatlowcostbestquality.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedRectangle358Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedEllipse19Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedSmartFarmingWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedRectangle359Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedLoginWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedSkipWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax16widget/generated/GeneratedRegisterWidget2.dart';

/* Frame iPhone 13 Pro Max - 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.46261699879227053,
                        translateY: constraints.maxHeight * 0.7533482142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse18Widget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.46261699879227053,
                        translateY: constraints.maxHeight * 0.7533482142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse19Widget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.39018743395229466,
                        translateY: constraints.maxHeight * 0.7533482142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse21Widget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.46261699879227053,
                        translateY: constraints.maxHeight * 0.7533482142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse22Widget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5350465636322463,
                        translateY: constraints.maxHeight * 0.7533482142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse20Widget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6074761284722222,
                        translateY: constraints.maxHeight * 0.7533482142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse23Widget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4830917874396135;

                  final double height =
                      constraints.maxHeight * 0.07366071428571429;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.27053140096618356,
                        y: constraints.maxHeight * 0.5323660714285714,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSmartFarmingWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7897195862111263;

                  final double height =
                      constraints.maxHeight * 0.21260935919625418;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10514018846594769,
                        y: constraints.maxHeight * 0.21382290976388113,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedScreenshot_20220403_173455removebgpreview1Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1497584541062802;

                  final double height =
                      constraints.maxHeight * 0.06138392857142857;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7536231884057971,
                        y: constraints.maxHeight * 0.06808035714285714,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSkipWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.35747664446992;

                  final double height =
                      constraints.maxHeight * 0.055075577327183316;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10386474351376151,
                        y: constraints.maxHeight * 0.8258928571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle358Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2946859903381642;

                  final double height =
                      constraints.maxHeight * 0.07700892857142858;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17149758454106281,
                        y: constraints.maxHeight * 0.8348214285714286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRegisterWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.35747664446992;

                  final double height =
                      constraints.maxHeight * 0.055075577327183316;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.533816425120773,
                        y: constraints.maxHeight * 0.8258928571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle359Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2318840579710145;

                  final double height =
                      constraints.maxHeight * 0.07700892857142858;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.642512077294686,
                        y: constraints.maxHeight * 0.8348214285714286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLoginWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7711860546167346;

                  final double height =
                      constraints.maxHeight * 0.0961845942905971;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1280193236714976,
                        y: constraints.maxHeight * 0.5970982142857143,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedBuyRentadvancedequipmentrequirementatlowcostbestquality(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
