import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedBxcurrentlocationWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedNumberboxWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedComponent5Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedComponent3Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedComponent4Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedComponent7Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedComponent1Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedTamilWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedComponent9Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedComponent6Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedContinueWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedComponent8Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedSelectyourlanguageWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedComponent2Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedRegisterboxWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedEnterstatedistrictWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedAutoDetectMyLocationWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax59widget/generated/GeneratedComponent10Widget1.dart';

/* Frame iPhone 11 Pro Max - 59
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax59Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 57.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent1Widget1(),
              ),
              Positioned(
                left: 228.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent2Widget1(),
              ),
              Positioned(
                left: 57.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent3Widget1(),
              ),
              Positioned(
                left: 228.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent4Widget1(),
              ),
              Positioned(
                left: 58.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent7Widget1(),
              ),
              Positioned(
                left: 228.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent6Widget1(),
              ),
              Positioned(
                left: 57.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent9Widget1(),
              ),
              Positioned(
                left: 231.0,
                top: 541.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent10Widget1(),
              ),
              Positioned(
                left: 191.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 128.0,
                child: GeneratedComponent5Widget1(),
              ),
              Positioned(
                left: 58.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent8Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.171497510827106;

                  final double height =
                      constraints.maxHeight * 0.033482142857142856;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6347125509510869,
                        y: constraints.maxHeight * 0.6211504255022321,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTamilWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 97.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 54.0,
                child: GeneratedSelectyourlanguageWidget1(),
              ),
              Positioned(
                left: 57.0,
                top: 725.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxcurrentlocationWidget1(),
              ),
              Positioned(
                left: null,
                top: 650.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 52.0,
                child: TransformHelper.translate(
                    x: 4.00, y: 0.00, z: 0, child: GeneratedNumberboxWidget1()),
              ),
              Positioned(
                left: 87.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 26.0,
                child: GeneratedEnterstatedistrictWidget1(),
              ),
              Positioned(
                left: 94.0,
                top: 725.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 22.0,
                child: GeneratedAutoDetectMyLocationWidget1(),
              ),
              Positioned(
                left: null,
                top: 789.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 53.0,
                child: TransformHelper.translate(
                    x: 4.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedRegisterboxWidget1()),
              ),
              Positioned(
                left: 165.0,
                top: 800.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 26.0,
                child: GeneratedContinueWidget2(),
              )
            ]),
      ),
    ));
  }
}
