import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedEllipse22Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedSellyourProductsdirectlythroughthisappWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedEllipse18Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedEllipse19Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedSkipWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedEllipse20Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedSmartFarmingWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedLoginWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedEllipse21Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedRegisterWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedScreenshot_20220403_180404removebgpreview1Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedRectangle358Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedEllipse23Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax19widget/generated/GeneratedRectangle359Widget2.dart';

/* Frame iPhone 13 Pro Max - 19
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax19Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.46261699879227053,
                        translateY: constraints.maxHeight * 0.7533482142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse18Widget2())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.46261699879227053,
                        translateY: constraints.maxHeight * 0.7533482142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse19Widget2())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.39018743395229466,
                        translateY: constraints.maxHeight * 0.7533482142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse21Widget2())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.46261699879227053,
                        translateY: constraints.maxHeight * 0.7533482142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse22Widget2())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6098125660477053,
                        translateY: constraints.maxHeight * 0.7533482142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse23Widget2())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5350465636322463,
                        translateY: constraints.maxHeight * 0.7533482142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse20Widget2())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.45893719806763283;

                  final double height =
                      constraints.maxHeight * 0.07366071428571429;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.27053140096618356,
                        y: constraints.maxHeight * 0.5323660714285714,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSmartFarmingWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7009345160590278;

                  final double height =
                      constraints.maxHeight * 0.22786174501691545;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1495327143277523,
                        y: constraints.maxHeight * 0.21166307585580008,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedScreenshot_20220403_180404removebgpreview1Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.20048309178743962;

                  final double height =
                      constraints.maxHeight * 0.06138392857142857;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7536231884057971,
                        y: constraints.maxHeight * 0.06808035714285714,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSkipWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.35747664446992;

                  final double height =
                      constraints.maxHeight * 0.055075577327183316;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10386474351376151,
                        y: constraints.maxHeight * 0.8258928571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle358Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3454107017332805;

                  final double height =
                      constraints.maxHeight * 0.07700892857142858;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17149758454106281,
                        y: constraints.maxHeight * 0.8348214285714286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRegisterWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.35747664446992;

                  final double height =
                      constraints.maxHeight * 0.055075577327183316;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5607473769625604,
                        y: constraints.maxHeight * 0.8258928571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle359Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2560386473429952;

                  final double height =
                      constraints.maxHeight * 0.07700892857142858;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6739130434782609,
                        y: constraints.maxHeight * 0.8348214285714286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLoginWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7711859809027778;

                  final double height =
                      constraints.maxHeight * 0.06486708777291435;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1280193236714976,
                        y: constraints.maxHeight * 0.5970982142857143,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedSellyourProductsdirectlythroughthisappWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
