import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedProcessingWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedEvaarrowbackfillWidget16.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedSubtotalWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedTotalWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedTaxesTransportationchargeWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedCancelWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/Generated0rderSummaryWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram5.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedEllipse141Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedEllipse140Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedEllipse143Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedRectangle2882Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedOrderplacedonMarch24Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedRectangle2882Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedTobedeliveredonApril2Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/Generated\$400Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedDeliveryAddressWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedOrderInfoWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/Generated\$450Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/Generated\$50Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax38widget/generated/GeneratedEllipse142Widget.dart';

/* Frame iPhone 11 Pro Max - 38
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax38Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 97.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 36.0,
                child: Generated0rderSummaryWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget16(),
              ),
              Positioned(
                left: 61.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse140Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse141Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedEllipse142Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse143Widget(),
              ),
              Positioned(
                left: 106.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 28.0,
                child: GeneratedOrderplacedonMarch24Widget(),
              ),
              Positioned(
                left: 106.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 28.0,
                child: GeneratedProcessingWidget(),
              ),
              Positioned(
                left: 106.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 28.0,
                child: GeneratedTobedeliveredonApril2Widget(),
              ),
              Positioned(
                left: 69.0,
                top: 189.97509765625,
                right: null,
                bottom: null,
                width: 40.04996871948242,
                height: 2.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 68.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 40.04996871948242,
                height: 2.0,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 28.0,
                child: GeneratedDeliveryAddressWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 28.0,
                child: GeneratedOrderInfoWidget(),
              ),
              Positioned(
                left: 70.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 371.0,
                height: 90.0,
                child:
                    GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram5(),
              ),
              Positioned(
                left: 40.0,
                top: 820.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 53.0,
                child: GeneratedRectangle2882Widget(),
              ),
              Positioned(
                left: 88.0,
                top: 831.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 34.0,
                child: GeneratedCancelWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 138.0,
                child: GeneratedRectangle2882Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 27.0,
                child: GeneratedSubtotalWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 708.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 24.0,
                child: GeneratedTaxesTransportationchargeWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 34.0,
                child: GeneratedTotalWidget(),
              ),
              Positioned(
                left: 321.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 28.0,
                child: Generated$400Widget(),
              ),
              Positioned(
                left: 321.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 31.0,
                child: Generated$450Widget1(),
              ),
              Positioned(
                left: 321.0,
                top: 707.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 28.0,
                child: Generated$50Widget(),
              )
            ]),
      ),
    ));
  }
}
