import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/Generated\$820Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/GeneratedRectangle2907Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/GeneratedGetitbyWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/GeneratedFrame268Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/GeneratedTotalWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/GeneratedDelivertoWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/Generated\$4820Widget7.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/GeneratedFrame268Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/Generated\$4000Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/GeneratedSubtotalWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/GeneratedFrame272Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/GeneratedFrame271Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax24widget/generated/GeneratedTaxesTransportationchargeWidget3.dart';

/* Frame iPhone 13 Pro Max - 24
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax24Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 243, 243, 243),
                      ),
                    ),
                    Positioned(
                      left: 20.0,
                      top: 73.0,
                      right: null,
                      bottom: null,
                      width: 372.0,
                      height: 137.0,
                      child: GeneratedFrame268Widget2(),
                    ),
                    Positioned(
                      left: 39.0,
                      top: 87.0,
                      right: null,
                      bottom: null,
                      width: 420.0,
                      height: 48.0,
                      child: GeneratedDelivertoWidget1(),
                    ),
                    Positioned(
                      left: 13.0,
                      top: 283.0,
                      right: null,
                      bottom: null,
                      width: 388.0,
                      height: 434.0,
                      child: GeneratedFrame268Widget3(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 233.0,
                      right: null,
                      bottom: null,
                      width: 420.0,
                      height: 48.0,
                      child: GeneratedGetitbyWidget1(),
                    ),
                    Positioned(
                      left: 12.0,
                      top: 756.0,
                      right: null,
                      bottom: null,
                      width: 388.0,
                      height: 156.0,
                      child: GeneratedRectangle2907Widget1(),
                    ),
                    Positioned(
                      left: 46.0,
                      top: 789.0,
                      right: null,
                      bottom: null,
                      width: 70.0,
                      height: 27.0,
                      child: GeneratedSubtotalWidget3(),
                    ),
                    Positioned(
                      left: 51.0,
                      top: 827.0,
                      right: null,
                      bottom: null,
                      width: 228.0,
                      height: 24.0,
                      child: GeneratedTaxesTransportationchargeWidget3(),
                    ),
                    Positioned(
                      left: 53.0,
                      top: 863.0,
                      right: null,
                      bottom: null,
                      width: 55.0,
                      height: 34.0,
                      child: GeneratedTotalWidget3(),
                    ),
                    Positioned(
                      left: 308.0,
                      top: 787.0,
                      right: null,
                      bottom: null,
                      width: 67.0,
                      height: 28.0,
                      child: Generated$4000Widget1(),
                    ),
                    Positioned(
                      left: 315.0,
                      top: 865.0,
                      right: null,
                      bottom: null,
                      width: 68.0,
                      height: 31.0,
                      child: Generated$4820Widget7(),
                    ),
                    Positioned(
                      left: 315.0,
                      top: 826.0,
                      right: null,
                      bottom: null,
                      width: 51.0,
                      height: 28.0,
                      child: Generated$820Widget1(),
                    ),
                    Positioned(
                      left: 20.0,
                      top: 952.0,
                      right: null,
                      bottom: null,
                      width: 383.0,
                      height: 165.0,
                      child: GeneratedFrame271Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: -7.0,
              top: 822.0,
              right: null,
              bottom: null,
              width: 499.0,
              height: 77.0,
              child: GeneratedFrame272Widget1(),
            )
          ]),
    ));
  }
}
