import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedTobedeliveredonApril2Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedOrderInfoWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/Generated\$450Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedRectangle2882Widget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/Generated\$400Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedOrderSummaryWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedTaxesTransportationchargeWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedOrderplacedonMarch24Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedLine8Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedEllipse142Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram7.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedEllipse143Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedEllipse141Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedEvaarrowbackfillWidget18.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedLine7Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedTotalWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedSubtotalWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedDeliveryAddressWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedRectangle2882Widget5.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/Generated\$50Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedProcessingWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedCancelWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax63widget/generated/GeneratedEllipse140Widget2.dart';

/* Frame iPhone 11 Pro Max - 63
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax63Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 97.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 44.0,
                child: GeneratedOrderSummaryWidget2(),
              ),
              Positioned(
                left: 40.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget18(),
              ),
              Positioned(
                left: 61.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse140Widget2(),
              ),
              Positioned(
                left: 61.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse141Widget2(),
              ),
              Positioned(
                left: 54.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedEllipse142Widget2(),
              ),
              Positioned(
                left: 61.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse143Widget2(),
              ),
              Positioned(
                left: 106.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 28.0,
                child: GeneratedOrderplacedonMarch24Widget2(),
              ),
              Positioned(
                left: 106.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 28.0,
                child: GeneratedProcessingWidget2(),
              ),
              Positioned(
                left: 106.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 28.0,
                child: GeneratedTobedeliveredonApril2Widget2(),
              ),
              Positioned(
                left: 69.0,
                top: 189.97509765625,
                right: null,
                bottom: null,
                width: 40.04996871948242,
                height: 2.0,
                child: GeneratedLine7Widget2(),
              ),
              Positioned(
                left: 68.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 40.04996871948242,
                height: 2.0,
                child: GeneratedLine8Widget2(),
              ),
              Positioned(
                left: 36.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 34.0,
                child: GeneratedDeliveryAddressWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 34.0,
                child: GeneratedOrderInfoWidget2(),
              ),
              Positioned(
                left: 52.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 371.0,
                height: 90.0,
                child:
                    GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram7(),
              ),
              Positioned(
                left: 34.0,
                top: 808.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 53.0,
                child: GeneratedRectangle2882Widget4(),
              ),
              Positioned(
                left: 73.0,
                top: 817.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 41.0,
                child: GeneratedCancelWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 138.0,
                child: GeneratedRectangle2882Widget5(),
              ),
              Positioned(
                left: 42.0,
                top: 659.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 27.0,
                child: GeneratedSubtotalWidget2(),
              ),
              Positioned(
                left: 40.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 24.0,
                child: GeneratedTaxesTransportationchargeWidget2(),
              ),
              Positioned(
                left: 42.0,
                top: 732.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 34.0,
                child: GeneratedTotalWidget2(),
              ),
              Positioned(
                left: 315.0,
                top: 657.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 28.0,
                child: Generated$400Widget1(),
              ),
              Positioned(
                left: 315.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 31.0,
                child: Generated$450Widget2(),
              ),
              Positioned(
                left: 315.0,
                top: 695.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 28.0,
                child: Generated$50Widget1(),
              )
            ]),
      ),
    ));
  }
}
