import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/Generated1Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedRectangle2884Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedVectorWidget97.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedRectangle2886Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/Generated4StrokeSprayerPumpWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/Generated\$200Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedRectangle2888Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedRectangle2878Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedSpray1Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedAkariconscircleminusfillWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedAkariconscircleminusfillWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedWatchlistWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedCultivatorWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedZiraPesticidesWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedPest1Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedRectangle2887Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedRectangle2913Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedEvaarrowbackfillWidget11.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/Generated\$150Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedVectorWidget95.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedRectangle2874Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedAkariconscircleminusfillWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedCutivator1Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedRectangle2890Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedRectangle2891Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/Generated\$300Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedVectorWidget96.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedAkariconsminusWidget6.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/Generated3Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedAkariconsminusWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/Generated1Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedAkariconsplusWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedRectangle2883Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedTotal3itemsWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax39widget/generated/GeneratedAkariconsminusWidget5.dart';

/* Frame iPhone 11 Pro Max - 39
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax39Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: -8.0,
                top: -35.0,
                right: null,
                bottom: null,
                width: 443.0,
                height: 206.0,
                child: GeneratedRectangle2913Widget1(),
              ),
              Positioned(
                left: 106.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 39.0,
                child: GeneratedWatchlistWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget11(),
              ),
              Positioned(
                left: 52.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 28.0,
                child: GeneratedTotal3itemsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 1.0,
                child: GeneratedLine9Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 209.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 136.0,
                child: GeneratedRectangle2874Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 136.0,
                child: GeneratedRectangle2884Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 136.0,
                child: GeneratedRectangle2888Widget(),
              ),
              Positioned(
                left: 160.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 28.0,
                child: GeneratedZiraPesticidesWidget(),
              ),
              Positioned(
                left: 151.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 206.0,
                height: 28.0,
                child: Generated4StrokeSprayerPumpWidget(),
              ),
              Positioned(
                left: 158.0,
                top: 621.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 31.0,
                child: GeneratedCultivatorWidget(),
              ),
              Positioned(
                left: 300.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 37.0,
                child: GeneratedRectangle2878Widget(),
              ),
              Positioned(
                left: 300.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 37.0,
                child: GeneratedRectangle2886Widget1(),
              ),
              Positioned(
                left: 300.0,
                top: 706.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 37.0,
                child: GeneratedRectangle2890Widget(),
              ),
              Positioned(
                left: 315.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 27.0,
                child: Generated$200Widget(),
              ),
              Positioned(
                left: 315.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 27.0,
                child: Generated$300Widget(),
              ),
              Positioned(
                left: 315.0,
                top: 713.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 27.0,
                child: Generated$150Widget(),
              ),
              Positioned(
                left: 172.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 37.0,
                child: GeneratedRectangle2883Widget2(),
              ),
              Positioned(
                left: 172.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 37.0,
                child: GeneratedRectangle2887Widget(),
              ),
              Positioned(
                left: 172.0,
                top: 664.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 37.0,
                child: GeneratedRectangle2891Widget(),
              ),
              Positioned(
                left: 224.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 27.0,
                child: Generated3Widget2(),
              ),
              Positioned(
                left: 224.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 27.0,
                child: Generated1Widget(),
              ),
              Positioned(
                left: 224.0,
                top: 672.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 27.0,
                child: Generated1Widget1(),
              ),
              Positioned(
                left: 373.0,
                top: 458.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedAkariconsplusWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.024922172804385568;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      10.317779541015625;

                  double percentHeight = 0.011519057410103934;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      10.321075439453125;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6004672580295138,
                        translateY: constraints.maxHeight * 0.3218142645699637,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget95())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.024922172804385568;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      10.317779541015625;

                  double percentHeight = 0.011519091469900948;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      10.32110595703125;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6004672580295138,
                        translateY: constraints.maxHeight * 0.5302375725337437,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget96())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.024922172804385568;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      10.317779541015625;

                  double percentHeight = 0.011519091469900948;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      10.32110595703125;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6004672580295138,
                        translateY: constraints.maxHeight * 0.7321814128330776,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget97())
                  ]);
                }),
              ),
              Positioned(
                left: 191.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 24.0,
                child: GeneratedAkariconsminusWidget4(),
              ),
              Positioned(
                left: 191.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 24.0,
                child: GeneratedAkariconsminusWidget5(),
              ),
              Positioned(
                left: 191.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 24.0,
                child: GeneratedAkariconsminusWidget6(),
              ),
              Positioned(
                left: 70.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 119.21705627441406,
                child: GeneratedPest1Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 105.0,
                child: GeneratedSpray1Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 94.55999755859375,
                height: 79.33589935302734,
                child: GeneratedCutivator1Widget(),
              ),
              Positioned(
                left: 361.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedAkariconscircleminusfillWidget(),
              ),
              Positioned(
                left: 358.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedAkariconscircleminusfillWidget1(),
              ),
              Positioned(
                left: 358.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedAkariconscircleminusfillWidget2(),
              )
            ]),
      ),
    ));
  }
}
