description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Cabin"
      fonts: 
        - 
          asset: "fonts/Cabin-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Cabin-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Cabin-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Cabin-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Poppins"
      fonts: 
        - 
          asset: "fonts/Poppins-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Poppins-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Poppins-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Poppins-300.ttf"
          style: "normal"
          weight: 300
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-900.ttf"
          style: "normal"
          weight: 900
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Purple Purse"
      fonts: 
        - 
          asset: "fonts/PurplePurse-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Lato"
      fonts: 
        - 
          asset: "fonts/Lato-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Lato-regular.ttf"
          style: "normal"
          weight: 800
        - 
          asset: "fonts/Lato-regular.ttf"
          style: "normal"
          weight: 600
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Inter-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
