import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedChart01Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedKgsWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedGroup680Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedAtourgivenlocationWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedSellforWidget5.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedAkariconsplusWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedQUANTITYWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/Generated\$19502200Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedAthomeaddressWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedTomatoWidget5.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedVectorWidget30.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedGroup58Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/Generated\$402Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedProceedtoSellWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedAkariconsminusWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedTomatoWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedSellforWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedLine1Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedVectorWidget33.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/Generated3Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/Generated\$585Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedLowHighPriceWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedRectangle22Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedRectangle31Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedGroupWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedEvaarrowbackfillWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedFOOTERWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedVectorWidget27.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedVectorWidget29.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax64widget/generated/GeneratedGroup681Widget2.dart';

/* Frame iPhone 11 Pro Max - 64
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax64Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 34.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 331.9999084472656,
                height: 26.0,
                child: GeneratedGroup58Widget2(),
              ),
              Positioned(
                left: 162.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 46.0,
                child: GeneratedTomatoWidget4(),
              ),
              Positioned(
                left: 35.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 28.0,
                child: GeneratedQUANTITYWidget2(),
              ),
              Positioned(
                left: 259.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 29.0,
                child: Generated3Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 17.0,
                child: GeneratedKgsWidget2(),
              ),
              Positioned(
                left: 307.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 24.0,
                child: GeneratedAkariconsplusWidget2(),
              ),
              Positioned(
                left: 211.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAkariconsminusWidget2(),
              ),
              Positioned(
                left: 242.0,
                top: 630.0,
                right: null,
                bottom: null,
                width: 45.0099983215332,
                height: 3.0,
                child: GeneratedLine1Widget2(),
              ),
              Positioned(
                left: null,
                top: 485.0,
                right: 44.0,
                bottom: null,
                width: 350.0,
                height: 72.0,
                child: GeneratedRectangle31Widget2(),
              ),
              Positioned(
                left: null,
                top: 530.0,
                right: 70.0,
                bottom: null,
                width: 93.0,
                height: 18.0,
                child: GeneratedLowHighPriceWidget2(),
              ),
              Positioned(
                left: null,
                top: 508.0,
                right: 42.0,
                bottom: null,
                width: 152.0,
                height: 24.0,
                child: Generated$19502200Widget2(),
              ),
              Positioned(
                left: 93.0,
                top: 507.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 41.0,
                child: GeneratedTomatoWidget5(),
              ),
              Positioned(
                left: 36.6685791015625,
                top: 116.74932861328125,
                right: null,
                bottom: null,
                width: 350.69622802734375,
                height: 309.5574035644531,
                child: GeneratedChart01Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06280193236714976;

                  final double height =
                      constraints.maxHeight * 0.027321338653564453;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1349496518932103,
                        y: constraints.maxHeight * 0.5494735581534249,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup681Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.08454108123042157;

                  final double height =
                      constraints.maxHeight * 0.03906223603657314;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.25382639935627077,
                        y: constraints.maxHeight * 0.05641810383115496,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup680Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 194.0,
                top: 655.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 32.0,
                child: GeneratedSellforWidget4(),
              ),
              Positioned(
                left: 194.0,
                top: 706.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 32.0,
                child: GeneratedSellforWidget5(),
              ),
              Positioned(
                left: 274.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 31.0,
                child: Generated$585Widget2(),
              ),
              Positioned(
                left: 281.0,
                top: 704.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 34.0,
                child: Generated$402Widget2(),
              ),
              Positioned(
                left: 34.0,
                top: 660.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 24.0,
                child: GeneratedAtourgivenlocationWidget2(),
              ),
              Positioned(
                left: 34.0,
                top: 711.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 24.0,
                child: GeneratedAthomeaddressWidget2(),
              ),
              Positioned(
                left: 166.0,
                top: 749.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 50.0,
                child: GeneratedRectangle22Widget2(),
              ),
              Positioned(
                left: 209.0,
                top: 758.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 31.0,
                child: GeneratedProceedtoSellWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04941577266379831;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 20.4581298828125;

                  double percentHeight = 0.021198698452540805;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      18.994033813476562;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8317757574256491,
                        translateY: constraints.maxHeight * 0.06587472983769008,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget27())
                  ]);
                }),
              ),
              Positioned(
                left: 45.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07476640784222147;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      30.953292846679688;

                  double percentHeight = 0.030237674713134766;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      27.09295654296875;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5747663341282646,
                        translateY: constraints.maxHeight * 0.9384448868887765,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget29())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.08878503329512002;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 36.75700378417969;

                  double percentHeight = 0.047516277858189175;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      42.5745849609375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.3644859940533477,
                        translateY: constraints.maxHeight * 0.9211662837437221,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget30())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 813.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 120.0,
                child: GeneratedFOOTERWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.07359815219750152;

                  final double height =
                      constraints.maxHeight * 0.035140582493373325;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7827102734846769,
                        y: constraints.maxHeight * 0.9330453191484723,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06474299592096448;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      26.803600311279297;

                  double percentHeight = 0.03131750651768276;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      28.06048583984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.1542056079072077,
                        translateY: constraints.maxHeight * 0.9362850870404925,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget33())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
