import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedOrderInfoWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedLine8Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram6.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedLine7Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedRectangle2882Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedOrderplacedonMarch24Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedSubtotalWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/Generated\$820Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedEllipse140Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedTaxesTransportationchargeWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedEllipse141Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedEvaarrowbackfillWidget17.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedTotalWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedDeliveryAddressWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedEllipse142Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedOrderSummaryWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedRectangle2882Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedCancelWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/Generated\$4000Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedTobedeliveredonApril2Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedEllipse143Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/GeneratedProcessingWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax57widget/generated/Generated\$4820Widget1.dart';

/* Frame iPhone 11 Pro Max - 57
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax57Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 94.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 44.0,
                child: GeneratedOrderSummaryWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget17(),
              ),
              Positioned(
                left: 61.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse140Widget1(),
              ),
              Positioned(
                left: 61.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse141Widget1(),
              ),
              Positioned(
                left: 54.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedEllipse142Widget1(),
              ),
              Positioned(
                left: 61.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse143Widget1(),
              ),
              Positioned(
                left: 103.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 28.0,
                child: GeneratedOrderplacedonMarch24Widget1(),
              ),
              Positioned(
                left: 103.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 28.0,
                child: GeneratedProcessingWidget1(),
              ),
              Positioned(
                left: 103.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 28.0,
                child: GeneratedTobedeliveredonApril2Widget1(),
              ),
              Positioned(
                left: 69.0,
                top: 189.97509765625,
                right: null,
                bottom: null,
                width: 40.04996871948242,
                height: 2.0,
                child: GeneratedLine7Widget1(),
              ),
              Positioned(
                left: 68.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 40.04996871948242,
                height: 2.0,
                child: GeneratedLine8Widget1(),
              ),
              Positioned(
                left: 36.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 34.0,
                child: GeneratedDeliveryAddressWidget1(),
              ),
              Positioned(
                left: 36.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 34.0,
                child: GeneratedOrderInfoWidget1(),
              ),
              Positioned(
                left: 70.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 371.0,
                height: 90.0,
                child:
                    GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram6(),
              ),
              Positioned(
                left: 40.0,
                top: 820.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 53.0,
                child: GeneratedRectangle2882Widget2(),
              ),
              Positioned(
                left: 76.0,
                top: 828.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 41.0,
                child: GeneratedCancelWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 138.0,
                child: GeneratedRectangle2882Widget3(),
              ),
              Positioned(
                left: 48.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 27.0,
                child: GeneratedSubtotalWidget1(),
              ),
              Positioned(
                left: 46.0,
                top: 708.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 24.0,
                child: GeneratedTaxesTransportationchargeWidget1(),
              ),
              Positioned(
                left: 48.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 34.0,
                child: GeneratedTotalWidget1(),
              ),
              Positioned(
                left: 310.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 28.0,
                child: Generated$4000Widget(),
              ),
              Positioned(
                left: 310.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 31.0,
                child: Generated$4820Widget1(),
              ),
              Positioned(
                left: 310.0,
                top: 707.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 28.0,
                child: Generated$820Widget(),
              )
            ]),
      ),
    ));
  }
}
