import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax32widget/generated/GeneratedFrame268Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax32widget/generated/GeneratedContinueWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax32widget/generated/GeneratedDelivertoWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax32widget/generated/GeneratedFrame268Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax32widget/generated/GeneratedGetitbyWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax32widget/generated/GeneratedFrame272Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax32widget/generated/GeneratedFrame281Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame iPhone 13 Pro Max - 32
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax32Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 137.0,
                child: GeneratedFrame268Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 48.0,
                child: GeneratedDelivertoWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 447.0,
                child: GeneratedFrame268Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 48.0,
                child: GeneratedGetitbyWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 782.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 67.0,
                child: GeneratedFrame272Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3743961352657005;

                  final double height =
                      constraints.maxHeight * 0.020089285714285716;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3647342995169082,
                        y: constraints.maxHeight * 0.8828125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedContinueWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 40.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 104.0,
                child: GeneratedFrame281Widget(),
              )
            ]),
      ),
    ));
  }
}
