import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedMapWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedEllipse133Widget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedSellatgivenlocationWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedEllipse130Widget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedSellathouseaddressWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedEllipse135Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedEllipse137Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedEllipse132Widget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedProcesstoSellWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedAverageWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedGoodWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedFertilisersUsedWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedTransportdutycutfrompriceWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedSellWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedEllipse128Widget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedEllipse131Widget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedEllipse134Widget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedQualityWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedAddressWidget8.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/Generated32pptWidget9.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedAddressWidget9.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedEllipse136Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/Generated32pptWidget8.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax52widget/generated/GeneratedComponent12Widget4.dart';

/* Frame iPhone 11 Pro Max - 52
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax52Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 42.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 47.0,
                child: GeneratedProcesstoSellWidget4(),
              ),
              Positioned(
                left: 44.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 40.0,
                child: GeneratedQualityWidget4(),
              ),
              Positioned(
                left: 102.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 29.0,
                child: GeneratedGoodWidget4(),
              ),
              Positioned(
                left: 183.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 29.0,
                child: GeneratedMapWidget4(),
              ),
              Positioned(
                left: 88.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: Generated32pptWidget8(),
              ),
              Positioned(
                left: 89.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: Generated32pptWidget9(),
              ),
              Positioned(
                left: 44.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 37.0,
                child: GeneratedFertilisersUsedWidget4(),
              ),
              Positioned(
                left: 87.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 29.0,
                child: GeneratedAverageWidget4(),
              ),
              Positioned(
                left: 50.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse128Widget4(),
              ),
              Positioned(
                left: 50.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse132Widget4(),
              ),
              Positioned(
                left: 50.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse133Widget4(),
              ),
              Positioned(
                left: 50.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse134Widget4(),
              ),
              Positioned(
                left: 50.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse130Widget4(),
              ),
              Positioned(
                left: 50.0,
                top: 208.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse131Widget4(),
              ),
              Positioned(
                left: 95.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 32.0,
                child: GeneratedSellatgivenlocationWidget4(),
              ),
              Positioned(
                left: 36.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 29.0,
                child: GeneratedAddressWidget8(),
              ),
              Positioned(
                left: 35.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 29.0,
                child: GeneratedAddressWidget9(),
              ),
              Positioned(
                left: 94.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 32.0,
                child: GeneratedSellathouseaddressWidget(),
              ),
              Positioned(
                left: 149.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 22.0,
                child: GeneratedComponent12Widget4(),
              ),
              Positioned(
                left: 130.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 23.0,
                child: GeneratedTransportdutycutfrompriceWidget4(),
              ),
              Positioned(
                left: 87.0,
                top: 672.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 90.0,
                child:
                    GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram4(),
              ),
              Positioned(
                left: 55.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedEllipse135Widget3(),
              ),
              Positioned(
                left: 230.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 54.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 276.0,
                top: 804.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 40.0,
                child: GeneratedSellWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedEllipse136Widget2(),
              ),
              Positioned(
                left: 55.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedEllipse137Widget1(),
              )
            ]),
      ),
    ));
  }
}
