import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedFrame274Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedSeeallWidget7.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedFrame280Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedDronesWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedSystemuiconsfilteringWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedSeeallWidget6.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedRectangle2865Widget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedRectangle2864Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedFrame279Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedSearchWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedPesticidesWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedFrame278Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedCultivatorWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedVectorWidget710.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedComponent15Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax28widget/generated/GeneratedSeeallWidget8.dart';

/* Frame iPhone 13 Pro Max - 28
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax28Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 243, 243, 243),
                      ),
                    ),
                    Positioned(
                      left: 37.0,
                      top: 54.0,
                      right: null,
                      bottom: null,
                      width: 286.0,
                      height: 53.0,
                      child: GeneratedRectangle2864Widget3(),
                    ),
                    Positioned(
                      left: 339.0,
                      top: 55.0,
                      right: null,
                      bottom: null,
                      width: 53.0,
                      height: 53.0,
                      child: GeneratedRectangle2865Widget4(),
                    ),
                    Positioned(
                      left: 95.0,
                      top: 66.0,
                      right: null,
                      bottom: null,
                      width: 113.0,
                      height: 26.0,
                      child: GeneratedSearchWidget3(),
                    ),
                    Positioned(
                      left: 351.0,
                      top: 66.0,
                      right: null,
                      bottom: null,
                      width: 28.0,
                      height: 28.0,
                      child: GeneratedSystemuiconsfilteringWidget3(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.05032712595474317;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            20.835430145263672;

                        double percentHeight = 0.022700893027441844;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                20.34000015258789;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.1401868442406401,
                              translateY:
                                  constraints.maxHeight * 0.07873123032706124,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget710())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 37.0,
                      top: 205.0,
                      right: null,
                      bottom: null,
                      width: 88.0,
                      height: 40.0,
                      child: GeneratedDronesWidget4(),
                    ),
                    Positioned(
                      left: 340.0,
                      top: 210.0,
                      right: null,
                      bottom: null,
                      width: 54.0,
                      height: 23.0,
                      child: GeneratedSeeallWidget6(),
                    ),
                    Positioned(
                      left: 35.0,
                      top: 255.0,
                      right: null,
                      bottom: null,
                      width: 394.0,
                      height: 204.0,
                      child: GeneratedFrame278Widget1(),
                    ),
                    Positioned(
                      left: 37.0,
                      top: 496.0,
                      right: null,
                      bottom: null,
                      width: 122.0,
                      height: 40.0,
                      child: GeneratedCultivatorWidget3(),
                    ),
                    Positioned(
                      left: 340.0,
                      top: 505.0,
                      right: null,
                      bottom: null,
                      width: 54.0,
                      height: 23.0,
                      child: GeneratedSeeallWidget7(),
                    ),
                    Positioned(
                      left: 35.0,
                      top: 552.0,
                      right: null,
                      bottom: null,
                      width: 393.0,
                      height: 204.0,
                      child: GeneratedFrame279Widget1(),
                    ),
                    Positioned(
                      left: 41.0,
                      top: 795.0,
                      right: null,
                      bottom: null,
                      width: 124.0,
                      height: 40.0,
                      child: GeneratedPesticidesWidget1(),
                    ),
                    Positioned(
                      left: 340.0,
                      top: 801.0,
                      right: null,
                      bottom: null,
                      width: 54.0,
                      height: 23.0,
                      child: GeneratedSeeallWidget8(),
                    ),
                    Positioned(
                      left: 35.0,
                      top: 847.0,
                      right: null,
                      bottom: null,
                      width: 391.0,
                      height: 211.0,
                      child: GeneratedFrame280Widget1(),
                    ),
                    Positioned(
                      left: 35.0,
                      top: 134.0,
                      right: null,
                      bottom: null,
                      width: 390.0,
                      height: 47.0,
                      child: GeneratedFrame274Widget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 4.547473508864641e-13,
              top: 813.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 88.0,
              child: GeneratedComponent15Widget1(),
            )
          ]),
    ));
  }
}
