import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedRectangle2878Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedRectangle2879Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedRectangle2913Widget5.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedMyOrdersWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedDownloadremovebgpreview2Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedRectangle2881Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedX1Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedTrackOrderWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/Generated\$70Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedOrderonMarch242022Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedRectangle2874Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedExecutedOrdersWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedDeepakFertilizersWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/Generated\$450Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedX2Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedPhoenixDroneWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedPest2Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax37widget/generated/GeneratedEvaarrowbackfillWidget15.dart';

/* Frame iPhone 11 Pro Max - 37
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax37Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: -7.0,
                top: -34.0,
                right: null,
                bottom: null,
                width: 443.0,
                height: 141.0,
                child: GeneratedRectangle2913Widget5(),
              ),
              Positioned(
                left: 97.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 36.0,
                child: GeneratedMyOrdersWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget15(),
              ),
              Positioned(
                left: 36.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 28.0,
                child: GeneratedOrderonMarch242022Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 28.0,
                child: GeneratedExecutedOrdersWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 122.0,
                child: GeneratedRectangle2874Widget2(),
              ),
              Positioned(
                left: 36.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 122.0,
                child: GeneratedRectangle2879Widget(),
              ),
              Positioned(
                left: 165.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 30.0,
                child: GeneratedPhoenixDroneWidget(),
              ),
              Positioned(
                left: 165.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 30.0,
                child: GeneratedDeepakFertilizersWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 28.0,
                child: GeneratedTrackOrderWidget(),
              ),
              Positioned(
                left: 166.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 27.0,
                child: GeneratedX2Widget(),
              ),
              Positioned(
                left: 166.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 27.0,
                child: GeneratedX1Widget(),
              ),
              Positioned(
                left: 297.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 37.0,
                child: GeneratedRectangle2878Widget1(),
              ),
              Positioned(
                left: 297.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 37.0,
                child: GeneratedRectangle2881Widget(),
              ),
              Positioned(
                left: 312.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 27.0,
                child: Generated$450Widget(),
              ),
              Positioned(
                left: 318.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 27.0,
                child: Generated$70Widget(),
              ),
              Positioned(
                left: 50.997772216796875,
                top: 351.5,
                right: null,
                bottom: null,
                width: 112.00446319580078,
                height: 2.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 70.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 112.09962463378906,
                child: GeneratedPest2Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 224.0,
                right: null,
                bottom: null,
                width: 91.62999725341797,
                height: 44.39218521118164,
                child: GeneratedDownloadremovebgpreview2Widget(),
              )
            ]),
      ),
    ));
  }
}
