import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedSellatgivenlocationWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedEllipse128Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedEvaarrowbackfillWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedEllipse133Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedSellathomeaddressWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedAverageWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedComponent12Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/Generated32pptWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedEllipse131Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedEllipse130Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/Generated32pptWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedQualityWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedGoodWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedAddressWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedEllipse132Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedEllipse134Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedAddressWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedTransportdutycutfrompriceWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedProcesstoSellWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedMapWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax48widget/generated/GeneratedFertilisersUsedWidget.dart';

/* Frame iPhone 11 Pro Max - 48
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax48Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 46.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 38.0,
                child: GeneratedProcesstoSellWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 40.0,
                child: GeneratedQualityWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 29.0,
                child: GeneratedGoodWidget(),
              ),
              Positioned(
                left: 191.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 29.0,
                child: GeneratedMapWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: Generated32pptWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 387.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: Generated32pptWidget1(),
              ),
              Positioned(
                left: 52.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 37.0,
                child: GeneratedFertilisersUsedWidget(),
              ),
              Positioned(
                left: 95.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 29.0,
                child: GeneratedAverageWidget(),
              ),
              Positioned(
                left: 58.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse128Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 387.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse132Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse133Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse134Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse130Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse131Widget(),
              ),
              Positioned(
                left: 103.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 32.0,
                child: GeneratedSellatgivenlocationWidget(),
              ),
              Positioned(
                left: 44.0,
                top: 666.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 29.0,
                child: GeneratedAddressWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 29.0,
                child: GeneratedAddressWidget1(),
              ),
              Positioned(
                left: 102.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 32.0,
                child: GeneratedSellathomeaddressWidget(),
              ),
              Positioned(
                left: 157.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 22.0,
                child: GeneratedComponent12Widget(),
              ),
              Positioned(
                left: 138.0,
                top: 630.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 23.0,
                child: GeneratedTransportdutycutfrompriceWidget(),
              ),
              Positioned(
                left: 92.0,
                top: 702.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 90.0,
                child:
                    GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram(),
              ),
              Positioned(
                left: 48.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget4(),
              )
            ]),
      ),
    ));
  }
}
