import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedVectorWidget638.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedRectangle2902Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedVectorWidget639.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedLine17Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedVectorWidget637.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedDownloadremovebgpreview1Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedIncludingalltaxesWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedBookmarkWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedSpeed010msWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedComponent18Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedDetailsWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedProcedureWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedMRPWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedViewmoreWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedRange3000mWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedVectorWidget635.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedFlowRate122LminWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/Generated\$4820Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedTotalWeight30kgWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedEvaarrowbackfillWidget20.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedCarbonfibredrone10LQuadcopterWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedVectorWidget636.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedRectangle2901Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedFlightTimeUpto25minWithLithiumIonUpto20minWithLipoWidge.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax9widget/generated/GeneratedSprayWidth45mWidget.dart';

/* Frame iPhone 13 Pro Max - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 40.0,
                      top: 64.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 30.0,
                      child: GeneratedEvaarrowbackfillWidget20(),
                    ),
                    Positioned(
                      left: 91.0,
                      top: 67.0,
                      right: null,
                      bottom: null,
                      width: 281.0,
                      height: 62.0,
                      child: GeneratedCarbonfibredrone10LQuadcopterWidget1(),
                    ),
                    Positioned(
                      left: 175.0,
                      top: 374.0,
                      right: null,
                      bottom: null,
                      width: 13.0,
                      height: 13.0,
                      child: GeneratedEllipse2Widget(),
                    ),
                    Positioned(
                      left: 203.0,
                      top: 374.0,
                      right: null,
                      bottom: null,
                      width: 13.0,
                      height: 13.0,
                      child: GeneratedEllipse3Widget(),
                    ),
                    Positioned(
                      left: 233.0,
                      top: 374.0,
                      right: null,
                      bottom: null,
                      width: 13.0,
                      height: 13.0,
                      child: GeneratedEllipse5Widget(),
                    ),
                    Positioned(
                      left: 131.0,
                      top: 428.0,
                      right: null,
                      bottom: null,
                      width: 98.0,
                      height: 33.0,
                      child: Generated$4820Widget2(),
                    ),
                    Positioned(
                      left: 45.0,
                      top: 426.0,
                      right: null,
                      bottom: null,
                      width: 68.0,
                      height: 41.0,
                      child: GeneratedMRPWidget(),
                    ),
                    Positioned(
                      left: 45.0,
                      top: 461.0,
                      right: null,
                      bottom: null,
                      width: 121.0,
                      height: 21.0,
                      child: GeneratedIncludingalltaxesWidget(),
                    ),
                    Positioned(
                      left: 49.0,
                      top: 519.0,
                      right: null,
                      bottom: null,
                      width: 131.0,
                      height: 41.0,
                      child: GeneratedRectangle2901Widget1(),
                    ),
                    Positioned(
                      left: 216.0,
                      top: 520.0,
                      right: null,
                      bottom: null,
                      width: 168.0,
                      height: 41.0,
                      child: GeneratedRectangle2902Widget(),
                    ),
                    Positioned(
                      left: 350.0,
                      top: 68.0,
                      right: null,
                      bottom: null,
                      width: 40.0,
                      height: 40.0,
                      child: GeneratedBookmarkWidget1(),
                    ),
                    Positioned(
                      left: 80.0,
                      top: 524.0,
                      right: null,
                      bottom: null,
                      width: 74.0,
                      height: 33.0,
                      child: GeneratedDetailsWidget(),
                    ),
                    Positioned(
                      left: 54.0,
                      top: 605.0,
                      right: null,
                      bottom: null,
                      width: 255.0,
                      height: 41.0,
                      child: GeneratedRange3000mWidget(),
                    ),
                    Positioned(
                      left: 54.0,
                      top: 644.0,
                      right: null,
                      bottom: null,
                      width: 308.0,
                      height: 26.0,
                      child: GeneratedSpeed010msWidget(),
                    ),
                    Positioned(
                      left: 53.0,
                      top: 684.0,
                      right: null,
                      bottom: null,
                      width: 247.0,
                      height: 33.0,
                      child: GeneratedFlowRate122LminWidget(),
                    ),
                    Positioned(
                      left: 53.0,
                      top: 720.0,
                      right: null,
                      bottom: null,
                      width: 204.0,
                      height: 50.0,
                      child: GeneratedSprayWidth45mWidget(),
                    ),
                    Positioned(
                      left: 53.0,
                      top: 740.0,
                      right: null,
                      bottom: null,
                      width: 238.0,
                      height: 56.0,
                      child: GeneratedTotalWeight30kgWidget(),
                    ),
                    Positioned(
                      left: 54.0,
                      top: 872.0,
                      right: null,
                      bottom: null,
                      width: 95.0,
                      height: 27.0,
                      child: GeneratedViewmoreWidget(),
                    ),
                    Positioned(
                      left: 54.0,
                      top: 780.0,
                      right: null,
                      bottom: null,
                      width: 384.0,
                      height: 98.0,
                      child:
                          GeneratedFlightTimeUpto25minWithLithiumIonUpto20minWithLipoWidge(),
                    ),
                    Positioned(
                      left: 59.0,
                      top: 179.0,
                      right: null,
                      bottom: null,
                      width: 322.0,
                      height: 156.0,
                      child: GeneratedDownloadremovebgpreview1Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.051086868064990944;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            21.14996337890625;

                        double percentHeight = 0.022094999040876116;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                19.797119140625;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.5887850701520985,
                              translateY:
                                  constraints.maxHeight * 0.47289092200142996,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget635())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.05108701549290459;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            21.1500244140625;

                        double percentHeight = 0.022094999040876116;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                19.797119140625;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.6491722070076615,
                              translateY:
                                  constraints.maxHeight * 0.47289092200142996,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget636())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.051086941778947764;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            21.149993896484375;

                        double percentHeight = 0.022094999040876116;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                19.797119140625;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.7095582381538723,
                              translateY:
                                  constraints.maxHeight * 0.47289092200142996,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget637())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.050724637681159424;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 21.0;

                        double percentHeight = 0.022613355091639926;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                20.261566162109375;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.7699453750094354,
                              translateY:
                                  constraints.maxHeight * 0.47289092200142996,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget638())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.050724637681159424;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 21.0;

                        double percentHeight = 0.02261338915143694;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                20.2615966796875;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.8303314061556462,
                              translateY:
                                  constraints.maxHeight * 0.47181098801749094,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget639())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 244.0,
                      top: 523.0,
                      right: null,
                      bottom: null,
                      width: 107.0,
                      height: 33.0,
                      child: GeneratedProcedureWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 499.0,
                      right: null,
                      bottom: null,
                      width: 428.0,
                      height: 1.0,
                      child: GeneratedLine17Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 738.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 169.0,
              child: GeneratedComponent18Widget(),
            )
          ]),
    ));
  }
}
