import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/GeneratedPinCodeWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/GeneratedScreenshot_20220403_164315removebg1Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/GeneratedPhoneNumberWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/GeneratedHellowelcometoAgrofastWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/GeneratedRegisterboxWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/GeneratedRegisterWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/GeneratedNumberboxWidget6.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/GeneratedAlreadyhaveaccountLoginhereWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/Generated521456Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/Generated9422034213Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/GeneratedRamaraoWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/GeneratedNumberboxWidget8.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax6widget/generated/GeneratedNumberboxWidget7.dart';

/* Frame iPhone 13 Pro Max - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: null,
                top: 725.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 55.0,
                child: TransformHelper.translate(
                    x: -5.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedRegisterboxWidget3()),
              ),
              Positioned(
                left: 157.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 26.0,
                child: GeneratedRegisterWidget(),
              ),
              Positioned(
                left: 66.0,
                top: 798.0,
                right: null,
                bottom: null,
                width: 296.0,
                height: 21.0,
                child: GeneratedAlreadyhaveaccountLoginhereWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 68.0,
                child: GeneratedHellowelcometoAgrofastWidget(),
              ),
              Positioned(
                left: null,
                top: 512.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 48.0,
                child: TransformHelper.translate(
                    x: 5.00, y: 0.00, z: 0, child: GeneratedNumberboxWidget6()),
              ),
              Positioned(
                left: null,
                top: 627.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 48.0,
                child: TransformHelper.translate(
                    x: 2.00, y: 0.00, z: 0, child: GeneratedNumberboxWidget7()),
              ),
              Positioned(
                left: 52.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 23.0,
                child: GeneratedPhoneNumberWidget1(),
              ),
              Positioned(
                left: 52.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 23.0,
                child: GeneratedPinCodeWidget(),
              ),
              Positioned(
                left: 74.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 26.0,
                child: Generated9422034213Widget2(),
              ),
              Positioned(
                left: 77.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 23.0,
                child: Generated521456Widget(),
              ),
              Positioned(
                left: null,
                top: 401.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 48.0,
                child: TransformHelper.translate(
                    x: 5.00, y: 0.00, z: 0, child: GeneratedNumberboxWidget8()),
              ),
              Positioned(
                left: 52.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 26.0,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 80.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 26.0,
                child: GeneratedRamaraoWidget1(),
              ),
              Positioned(
                left: 89.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 168.0,
                child: GeneratedScreenshot_20220403_164315removebg1Widget(),
              )
            ]),
      ),
    ));
  }
}
