import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedComponent10Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedComponent6Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedBxcurrentlocationWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedSelectyourlanguageWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedComponent8Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedComponent4Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedComponent9Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedNumberboxWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedComponent3Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedComponent1Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedContinueWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedRegisterboxWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedComponent7Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedAutoDetectMyLocationWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedTamilWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedComponent2Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedEnterstatedistrictWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax32widget/generated/GeneratedComponent5Widget.dart';

/* Frame iPhone 11 Pro Max - 32
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax32Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 55.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent1Widget(),
              ),
              Positioned(
                left: 226.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent2Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent3Widget(),
              ),
              Positioned(
                left: 226.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent4Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent7Widget(),
              ),
              Positioned(
                left: 226.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent6Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent9Widget(),
              ),
              Positioned(
                left: 229.0,
                top: 541.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent10Widget(),
              ),
              Positioned(
                left: 189.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 128.0,
                child: GeneratedComponent5Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 65.0,
                child: GeneratedComponent8Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.17149758454106281;

                  final double height =
                      constraints.maxHeight * 0.033482142857142856;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6350286363979468,
                        y: constraints.maxHeight * 0.6206490652901786,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTamilWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 97.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 54.0,
                child: GeneratedSelectyourlanguageWidget(),
              ),
              Positioned(
                left: 57.0,
                top: 725.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxcurrentlocationWidget(),
              ),
              Positioned(
                left: null,
                top: 650.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 52.0,
                child: TransformHelper.translate(
                    x: 4.00, y: 0.00, z: 0, child: GeneratedNumberboxWidget()),
              ),
              Positioned(
                left: 87.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 26.0,
                child: GeneratedEnterstatedistrictWidget(),
              ),
              Positioned(
                left: 94.0,
                top: 725.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 22.0,
                child: GeneratedAutoDetectMyLocationWidget(),
              ),
              Positioned(
                left: null,
                top: 785.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 53.0,
                child: TransformHelper.translate(
                    x: 4.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedRegisterboxWidget()),
              ),
              Positioned(
                left: 165.0,
                top: 795.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 26.0,
                child: GeneratedContinueWidget1(),
              )
            ]),
      ),
    ));
  }
}
