import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax36widget/generated/GeneratedComponent13Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax36widget/generated/GeneratedFrame287Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax36widget/generated/GeneratedComponent20Widget.dart';

/* Frame iPhone 13 Pro Max - 36
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax36Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 7.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 402.0,
                height: 921.0,
                child: GeneratedFrame287Widget(),
              ),
              Positioned(
                left: -8.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 427.0,
                height: 113.0,
                child: GeneratedComponent20Widget(),
              ),
              Positioned(
                left: -16.0,
                top: 807.0,
                right: null,
                bottom: null,
                width: 443.0,
                height: 91.0,
                child: GeneratedComponent13Widget(),
              )
            ]),
      ),
    ));
  }
}
