import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedImage4Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/Generated\$4820Widget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedMRPWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedBookmarkWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedRectangle2901Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedEllipse3Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedIncludingalltaxesWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedDownloadremovebgpreview1Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedComponent18Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedLine17Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedEllipse2Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedVectorWidget659.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedVectorWidget663.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedEllipse5Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedProcedureWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedCiplaycirclefilledWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedVectorWidget662.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedVectorWidget660.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedCarbonfibredrone10LQuadcopterWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedFlightTimeUpto25minWithLithiumIonUpto20minWithLipoWidge2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedTotalWeight30kgWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedViewmoreWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedRectangle2902Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedEvaarrowbackfillWidget22.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedVectorWidget661.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax37widget/generated/GeneratedDetailsWidget2.dart';

/* Frame iPhone 13 Pro Max - 37
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax37Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 40.0,
                      top: 64.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 30.0,
                      child: GeneratedEvaarrowbackfillWidget22(),
                    ),
                    Positioned(
                      left: 91.0,
                      top: 67.0,
                      right: null,
                      bottom: null,
                      width: 281.0,
                      height: 62.0,
                      child: GeneratedCarbonfibredrone10LQuadcopterWidget3(),
                    ),
                    Positioned(
                      left: 175.0,
                      top: 374.0,
                      right: null,
                      bottom: null,
                      width: 13.0,
                      height: 13.0,
                      child: GeneratedEllipse2Widget2(),
                    ),
                    Positioned(
                      left: 203.0,
                      top: 374.0,
                      right: null,
                      bottom: null,
                      width: 13.0,
                      height: 13.0,
                      child: GeneratedEllipse3Widget2(),
                    ),
                    Positioned(
                      left: 233.0,
                      top: 374.0,
                      right: null,
                      bottom: null,
                      width: 13.0,
                      height: 13.0,
                      child: GeneratedEllipse5Widget2(),
                    ),
                    Positioned(
                      left: 131.0,
                      top: 428.0,
                      right: null,
                      bottom: null,
                      width: 98.0,
                      height: 33.0,
                      child: Generated$4820Widget4(),
                    ),
                    Positioned(
                      left: 45.0,
                      top: 426.0,
                      right: null,
                      bottom: null,
                      width: 68.0,
                      height: 41.0,
                      child: GeneratedMRPWidget2(),
                    ),
                    Positioned(
                      left: 45.0,
                      top: 461.0,
                      right: null,
                      bottom: null,
                      width: 121.0,
                      height: 21.0,
                      child: GeneratedIncludingalltaxesWidget2(),
                    ),
                    Positioned(
                      left: 49.0,
                      top: 519.0,
                      right: null,
                      bottom: null,
                      width: 131.0,
                      height: 41.0,
                      child: GeneratedRectangle2901Widget3(),
                    ),
                    Positioned(
                      left: 216.0,
                      top: 520.0,
                      right: null,
                      bottom: null,
                      width: 168.0,
                      height: 41.0,
                      child: GeneratedRectangle2902Widget2(),
                    ),
                    Positioned(
                      left: 350.0,
                      top: 68.0,
                      right: null,
                      bottom: null,
                      width: 40.0,
                      height: 40.0,
                      child: GeneratedBookmarkWidget3(),
                    ),
                    Positioned(
                      left: 80.0,
                      top: 524.0,
                      right: null,
                      bottom: null,
                      width: 74.0,
                      height: 33.0,
                      child: GeneratedDetailsWidget2(),
                    ),
                    Positioned(
                      left: 53.0,
                      top: 740.0,
                      right: null,
                      bottom: null,
                      width: 238.0,
                      height: 56.0,
                      child: GeneratedTotalWeight30kgWidget2(),
                    ),
                    Positioned(
                      left: 54.0,
                      top: 872.0,
                      right: null,
                      bottom: null,
                      width: 95.0,
                      height: 27.0,
                      child: GeneratedViewmoreWidget2(),
                    ),
                    Positioned(
                      left: 54.0,
                      top: 780.0,
                      right: null,
                      bottom: null,
                      width: 384.0,
                      height: 98.0,
                      child:
                          GeneratedFlightTimeUpto25minWithLithiumIonUpto20minWithLipoWidge2(),
                    ),
                    Positioned(
                      left: 59.0,
                      top: 179.0,
                      right: null,
                      bottom: null,
                      width: 322.0,
                      height: 156.0,
                      child: GeneratedDownloadremovebgpreview1Widget3(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.051086868064990944;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            21.14996337890625;

                        double percentHeight = 0.022094999040876116;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                19.797119140625;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.5887850701520985,
                              translateY:
                                  constraints.maxHeight * 0.47289092200142996,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget659())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.05108701549290459;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            21.1500244140625;

                        double percentHeight = 0.022094999040876116;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                19.797119140625;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.6491722070076615,
                              translateY:
                                  constraints.maxHeight * 0.47289092200142996,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget660())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.051086941778947764;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            21.149993896484375;

                        double percentHeight = 0.022094999040876116;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                19.797119140625;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.7095582381538723,
                              translateY:
                                  constraints.maxHeight * 0.47289092200142996,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget661())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.050724637681159424;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 21.0;

                        double percentHeight = 0.022613355091639926;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                20.261566162109375;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.7699453750094354,
                              translateY:
                                  constraints.maxHeight * 0.47289092200142996,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget662())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.050724637681159424;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 21.0;

                        double percentHeight = 0.02261338915143694;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                20.2615966796875;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.8303314061556462,
                              translateY:
                                  constraints.maxHeight * 0.47181098801749094,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget663())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 244.0,
                      top: 525.0,
                      right: null,
                      bottom: null,
                      width: 107.0,
                      height: 33.0,
                      child: GeneratedProcedureWidget2(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 499.0,
                      right: null,
                      bottom: null,
                      width: 428.0,
                      height: 1.0,
                      child: GeneratedLine17Widget2(),
                    ),
                    Positioned(
                      left: 51.0,
                      top: 582.0,
                      right: null,
                      bottom: null,
                      width: 329.0,
                      height: 170.0,
                      child: GeneratedImage4Widget(),
                    ),
                    Positioned(
                      left: 194.0,
                      top: 651.0,
                      right: null,
                      bottom: null,
                      width: 32.0,
                      height: 32.0,
                      child: GeneratedCiplaycirclefilledWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 4.547473508864641e-13,
              top: 738.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 169.0,
              child: GeneratedComponent18Widget2(),
            )
          ]),
    ));
  }
}
