import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedSeeallWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedRectangle2865Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedSystemuiconsfilteringWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedFrame275Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedFrame277Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedTrendingWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedSearchWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedPriceUpWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedComponent14Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedFrame276Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedSeeallWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedVectorWidget696.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedFavouritesWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedSeeallWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax25widget/generated/GeneratedRectangle2864Widget1.dart';

/* Frame iPhone 13 Pro Max - 25
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax25Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 243, 243, 243),
                      ),
                    ),
                    Positioned(
                      left: 37.0,
                      top: 59.0,
                      right: null,
                      bottom: null,
                      width: 286.0,
                      height: 53.0,
                      child: GeneratedRectangle2864Widget1(),
                    ),
                    Positioned(
                      left: 328.0,
                      top: 59.0,
                      right: null,
                      bottom: null,
                      width: 53.0,
                      height: 53.0,
                      child: GeneratedRectangle2865Widget2(),
                    ),
                    Positioned(
                      left: 92.0,
                      top: 72.0,
                      right: null,
                      bottom: null,
                      width: 113.0,
                      height: 26.0,
                      child: GeneratedSearchWidget1(),
                    ),
                    Positioned(
                      left: 340.0,
                      top: 70.0,
                      right: null,
                      bottom: null,
                      width: 28.0,
                      height: 28.0,
                      child: GeneratedSystemuiconsfilteringWidget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.05032712595474317;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            20.835430145263672;

                        double percentHeight = 0.024218750851494924;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                21.700000762939453;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.1401874339522947,
                              translateY:
                                  constraints.maxHeight * 0.08452374594552177,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget696())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 37.0,
                      top: 495.0,
                      right: null,
                      bottom: null,
                      width: 391.0,
                      height: 217.0,
                      child: GeneratedFrame275Widget(),
                    ),
                    Positioned(
                      left: 37.0,
                      top: 143.0,
                      right: null,
                      bottom: null,
                      width: 128.0,
                      height: 40.0,
                      child: GeneratedFavouritesWidget(),
                    ),
                    Positioned(
                      left: 329.0,
                      top: 148.0,
                      right: null,
                      bottom: null,
                      width: 54.0,
                      height: 23.0,
                      child: GeneratedSeeallWidget(),
                    ),
                    Positioned(
                      left: 37.0,
                      top: 441.0,
                      right: null,
                      bottom: null,
                      width: 110.0,
                      height: 40.0,
                      child: GeneratedTrendingWidget(),
                    ),
                    Positioned(
                      left: 329.0,
                      top: 450.0,
                      right: null,
                      bottom: null,
                      width: 54.0,
                      height: 23.0,
                      child: GeneratedSeeallWidget1(),
                    ),
                    Positioned(
                      left: 37.0,
                      top: 745.0,
                      right: null,
                      bottom: null,
                      width: 97.0,
                      height: 37.0,
                      child: GeneratedPriceUpWidget(),
                    ),
                    Positioned(
                      left: 325.0,
                      top: 754.0,
                      right: null,
                      bottom: null,
                      width: 54.0,
                      height: 23.0,
                      child: GeneratedSeeallWidget2(),
                    ),
                    Positioned(
                      left: 28.0,
                      top: 794.0,
                      right: null,
                      bottom: null,
                      width: 400.0,
                      height: 204.0,
                      child: GeneratedFrame276Widget(),
                    ),
                    Positioned(
                      left: 37.0,
                      top: 192.0,
                      right: null,
                      bottom: null,
                      width: 395.0,
                      height: 204.0,
                      child: GeneratedFrame277Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 813.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 134.0,
              child: GeneratedComponent14Widget(),
            )
          ]),
    ));
  }
}
