import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedSkipWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedRectangle359Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedEllipse20Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedRegisterWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedRectangle358Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedEllipse19Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedEllipse21Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedScreenshot_20220403_172943removebgpreview1Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedEllipse18Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedSmartFarmingWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedEllipse22Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedObserveSensorsDataoffarmland247Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedEllipse23Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax15widget/generated/GeneratedLoginWidget.dart';

/* Frame iPhone 13 Pro Max - 15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7991884388209541;

                  final double height =
                      constraints.maxHeight * 0.21706267765590123;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10046728567224769,
                        y: constraints.maxHeight * 0.20194384029933385,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedScreenshot_20220403_172943removebgpreview1Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.35747664446992;

                  final double height =
                      constraints.maxHeight * 0.055075577327183316;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10386474351376151,
                        y: constraints.maxHeight * 0.8258928571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle358Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2971014492753623;

                  final double height =
                      constraints.maxHeight * 0.07700892857142858;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17149758454106281,
                        y: constraints.maxHeight * 0.8348214285714286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRegisterWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.35747664446992;

                  final double height =
                      constraints.maxHeight * 0.055075577327183316;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.533816425120773,
                        y: constraints.maxHeight * 0.8258928571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle359Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3115942028985507;

                  final double height =
                      constraints.maxHeight * 0.07700892857142858;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.642512077294686,
                        y: constraints.maxHeight * 0.8348214285714286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLoginWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.46261699879227053,
                        translateY: constraints.maxHeight * 0.7534542083740234,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse18Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.46261699879227053,
                        translateY: constraints.maxHeight * 0.7534542083740234,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse19Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.39018743395229466,
                        translateY: constraints.maxHeight * 0.7534542083740234,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse21Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.46261699879227053,
                        translateY: constraints.maxHeight * 0.7534542083740234,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse22Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5350465636322463,
                        translateY: constraints.maxHeight * 0.7534542083740234,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse20Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028037398333710748;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 11.60748291015625;

                  double percentHeight = 0.012959003448486328;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.61126708984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6074761284722222,
                        translateY: constraints.maxHeight * 0.7534542083740234,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse23Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5265700483091788;

                  final double height =
                      constraints.maxHeight * 0.08370535714285714;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.27053140096618356,
                        y: constraints.maxHeight * 0.5323660714285714,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSmartFarmingWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8179150272682669;

                  final double height =
                      constraints.maxHeight * 0.06486715589250837;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1280193236714976,
                        y: constraints.maxHeight * 0.5970982142857143,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedObserveSensorsDataoffarmland247Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.20048309178743962;

                  final double height =
                      constraints.maxHeight * 0.06138392857142857;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7536231884057971,
                        y: constraints.maxHeight * 0.06808035714285714,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSkipWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
