import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedArrowsupWidget5.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedEnglishWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedDeleteAccountWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedMinotificationWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedLanguageWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedFasolidtoggleonWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedRectangle2870Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedRectangle2872Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedEvaarrowbackfillWidget13.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedRectangle2913Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedNotificationsWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedBxhelpcircleWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedRectangle2871Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedHelpWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedSettingsWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax41widget/generated/GeneratedIcroundlanguageWidget.dart';

/* Frame iPhone 11 Pro Max - 41
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax41Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -99.0,
                right: null,
                bottom: null,
                width: 443.0,
                height: 206.0,
                child: GeneratedRectangle2913Widget3(),
              ),
              Positioned(
                left: 106.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 39.0,
                child: GeneratedSettingsWidget1(),
              ),
              Positioned(
                left: 39.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget13(),
              ),
              Positioned(
                left: 46.0,
                top: 167.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 43.0,
                child: GeneratedRectangle2870Widget1(),
              ),
              Positioned(
                left: 47.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 43.0,
                child: GeneratedRectangle2871Widget1(),
              ),
              Positioned(
                left: 47.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 43.0,
                child: GeneratedRectangle2872Widget1(),
              ),
              Positioned(
                left: 56.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcroundlanguageWidget(),
              ),
              Positioned(
                left: 116.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 33.0,
                child: GeneratedLanguageWidget(),
              ),
              Positioned(
                left: 116.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 30.0,
                child: GeneratedNotificationsWidget(),
              ),
              Positioned(
                left: 47.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 30.0,
                child: GeneratedDeleteAccountWidget(),
              ),
              Positioned(
                left: 116.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 33.0,
                child: GeneratedHelpWidget(),
              ),
              Positioned(
                left: 278.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 27.0,
                child: GeneratedEnglishWidget3(),
              ),
              Positioned(
                left: 385.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrowsupWidget5(),
              ),
              Positioned(
                left: 56.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMinotificationWidget(),
              ),
              Positioned(
                left: 344.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 30.0,
                child: GeneratedFasolidtoggleonWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxhelpcircleWidget(),
              )
            ]),
      ),
    ));
  }
}
