import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax62widget/generated/GeneratedRentOrderPlacedWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax62widget/generated/GeneratedLine13Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax62widget/generated/Generated0rderSummaryWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax62widget/generated/GeneratedTeenyiconstickcirclesolidWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax62widget/generated/GeneratedTrackyourOrderfromWidget1.dart';

/* Frame iPhone 11 Pro Max - 62
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax62Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 114.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 200.0,
                child: GeneratedTeenyiconstickcirclesolidWidget2(),
              ),
              Positioned(
                left: 68.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 50.0,
                child: GeneratedRentOrderPlacedWidget(),
              ),
              Positioned(
                left: 58.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 61.0,
                child: GeneratedTrackyourOrderfromWidget1(),
              ),
              Positioned(
                left: 118.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 36.0,
                child: Generated0rderSummaryWidget(),
              ),
              Positioned(
                left: 124.0,
                top: 528.5,
                right: null,
                bottom: null,
                width: 179.47145080566406,
                height: 3.0,
                child: GeneratedLine13Widget1(),
              )
            ]),
      ),
    ));
  }
}
