import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax53widget/generated/GeneratedTeenyiconstickcirclesolidWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax53widget/generated/GeneratedSellOrderPlacedWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax53widget/generated/GeneratedOrderwillbetakenfromhouseaddressin34daysWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax53widget/generated/GeneratedMoneywillbetransferedtoyouraccountinaweekWidget.dart';

/* Frame iPhone 11 Pro Max - 53
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax53Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 114.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 200.0,
                child: GeneratedTeenyiconstickcirclesolidWidget(),
              ),
              Positioned(
                left: 77.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 50.0,
                child: GeneratedSellOrderPlacedWidget(),
              ),
              Positioned(
                left: 58.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 61.0,
                child:
                    GeneratedOrderwillbetakenfromhouseaddressin34daysWidget(),
              ),
              Positioned(
                left: 66.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 61.0,
                child:
                    GeneratedMoneywillbetransferedtoyouraccountinaweekWidget(),
              )
            ]),
      ),
    ));
  }
}
