import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax23widget/generated/GeneratedAkariconsplusWidget6.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax23widget/generated/GeneratedEvaarrowbackfillWidget24.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax23widget/generated/GeneratedMapsicleMapWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax23widget/generated/GeneratedRectangle2863Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax23widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax23widget/generated/GeneratedAkariconsminusWidget9.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax23widget/generated/GeneratedCilocationWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax23widget/generated/GeneratedSwarnacoldstorageWidget.dart';

/* Frame iPhone 13 Pro Max - 23
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax23Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -266.0,
                top: -74.0,
                right: null,
                bottom: null,
                width: 2000.0,
                height: 2000.0,
                child: GeneratedMapsicleMapWidget(),
              ),
              Positioned(
                left: 157.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 30.0,
                child: GeneratedSwarnacoldstorageWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedEvaarrowbackfillWidget24(),
              ),
              Positioned(
                left: 214.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedCilocationWidget(),
              ),
              Positioned(
                left: 158.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 40.0,
                child: GeneratedRectangle2863Widget(),
              ),
              Positioned(
                left: 227.0,
                top: 824.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAkariconsplusWidget6(),
              ),
              Positioned(
                left: 174.0,
                top: 823.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAkariconsminusWidget9(),
              ),
              Positioned(
                left: 211.0,
                top: 815.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 2.0,
                child: GeneratedLine2Widget(),
              )
            ]),
      ),
    ));
  }
}
