import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax35widget/generated/GeneratedFrame268Widget11.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax35widget/generated/GeneratedFrame272Widget5.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax35widget/generated/GeneratedFrame268Widget10.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax35widget/generated/GeneratedFrame281Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax35widget/generated/GeneratedContinueWidget8.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax35widget/generated/GeneratedContinueWidget9.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax35widget/generated/GeneratedDelivertoWidget5.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax35widget/generated/GeneratedGetitbyWidget5.dart';

/* Frame iPhone 13 Pro Max - 35
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax35Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: 21.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 137.0,
                child: GeneratedFrame268Widget10(),
              ),
              Positioned(
                left: 43.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 48.0,
                child: GeneratedDelivertoWidget5(),
              ),
              Positioned(
                left: 15.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 447.0,
                child: GeneratedFrame268Widget11(),
              ),
              Positioned(
                left: 23.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 48.0,
                child: GeneratedGetitbyWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2854417441547781;

                  final double height =
                      constraints.maxHeight * 0.030790397099086216;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3617544865262681,
                        y: constraints.maxHeight * 0.6099440029689244,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedContinueWidget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 34.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 104.0,
                child: GeneratedFrame281Widget3(),
              ),
              Positioned(
                left: 14.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 77.0,
                child: GeneratedFrame272Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4420289855072464;

                  final double height = constraints.maxHeight * 0.03125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.35990338164251207,
                        y: constraints.maxHeight * 0.8683035714285714,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedContinueWidget9(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
