import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax56widget/generated/GeneratedEvaarrowbackfillWidget8.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax56widget/generated/GeneratedTeenyiconstickcirclesolidWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax56widget/generated/GeneratedTrackyourOrderfromWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax56widget/generated/GeneratedLine13Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax56widget/generated/GeneratedBuyOrderPlacedWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax56widget/generated/GeneratedOrderSummaryWidget.dart';

/* Frame iPhone 11 Pro Max - 56
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax56Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 111.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 200.0,
                child: GeneratedTeenyiconstickcirclesolidWidget1(),
              ),
              Positioned(
                left: 75.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 50.0,
                child: GeneratedBuyOrderPlacedWidget(),
              ),
              Positioned(
                left: 58.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 61.0,
                child: GeneratedTrackyourOrderfromWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 44.0,
                child: GeneratedOrderSummaryWidget(),
              ),
              Positioned(
                left: 121.0,
                top: 528.5,
                right: null,
                bottom: null,
                width: 179.47145080566406,
                height: 3.0,
                child: GeneratedLine13Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget8(),
              )
            ]),
      ),
    ));
  }
}
