import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedFOOTERWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedRectangle2914Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedDoctorcheckedplant178609341Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/Generated45Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedDrSurekhaWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedRectangle2909Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedLine11Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedScreenShot20170525at3481Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedDrsuryaWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedRecommendedWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedExperienceof6yrsWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedAgroDoctorWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedAgronomistWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedRectangle2910Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedVectorWidget49.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedChatWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedScreenShot20170525at3482Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedAgrologistWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedGroupWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedExperienceof8yrsWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedVectorWidget46.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/Generated40Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedDrRameshWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedChatWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedVectorWidget45.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedAgrochemistWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedRectangle2915Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedRectangle2912Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedExperienceof10yrsWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedRectangle2916Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/Generated35Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedLine12Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedChatWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax54widget/generated/GeneratedRectangle2901Widget.dart';

/* Frame iPhone 11 Pro Max - 54
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax54Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 102.0,
                child: GeneratedRectangle2914Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 49.0,
                child: GeneratedAgroDoctorWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 35.0,
                child: GeneratedRecommendedWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 159.0,
                child: GeneratedRectangle2901Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 368.0,
                height: 158.0,
                child: GeneratedRectangle2910Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 368.0,
                height: 158.0,
                child: GeneratedRectangle2912Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 133.0,
                child: GeneratedRectangle2909Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 133.0,
                child: GeneratedRectangle2915Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 632.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 133.0,
                child: GeneratedRectangle2916Widget(),
              ),
              Positioned(
                left: 192.0,
                top: 147.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 34.0,
                child: GeneratedDrRameshWidget(),
              ),
              Positioned(
                left: 192.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 34.0,
                child: GeneratedDrSurekhaWidget(),
              ),
              Positioned(
                left: 192.0,
                top: 635.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 34.0,
                child: GeneratedDrsuryaWidget(),
              ),
              Positioned(
                left: 192.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 23.0,
                child: Generated45Widget(),
              ),
              Positioned(
                left: 192.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 23.0,
                child: Generated40Widget(),
              ),
              Positioned(
                left: 192.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 23.0,
                child: Generated35Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 34.0,
                child: GeneratedChatWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 34.0,
                child: GeneratedChatWidget1(),
              ),
              Positioned(
                left: 52.0,
                top: 786.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 34.0,
                child: GeneratedChatWidget2(),
              ),
              Positioned(
                left: 35.975341796875,
                top: 329.5,
                right: null,
                bottom: null,
                width: 91.0494384765625,
                height: 3.0,
                child: GeneratedLine10Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 91.0494384765625,
                height: 3.0,
                child: GeneratedLine11Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 821.0,
                right: null,
                bottom: null,
                width: 91.0494384765625,
                height: 3.0,
                child: GeneratedLine12Widget(),
              ),
              Positioned(
                left: 192.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 28.0,
                child: GeneratedAgrochemistWidget(),
              ),
              Positioned(
                left: 192.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 25.0,
                child: GeneratedExperienceof8yrsWidget(),
              ),
              Positioned(
                left: 192.0,
                top: 697.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 28.0,
                child: GeneratedAgronomistWidget(),
              ),
              Positioned(
                left: 192.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 25.0,
                child: GeneratedExperienceof6yrsWidget(),
              ),
              Positioned(
                left: 192.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 28.0,
                child: GeneratedAgrologistWidget(),
              ),
              Positioned(
                left: 192.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 25.0,
                child: GeneratedExperienceof10yrsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07476633412826464;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      30.953262329101562;

                  double percentHeight = 0.030237606593540738;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      27.0928955078125;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5700937169761473,
                        translateY: constraints.maxHeight * 0.9363934653145927,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget45())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06542058382633227;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      27.084121704101562;

                  double percentHeight = 0.03455720629010882;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      30.9632568359375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.35513969089673914,
                        translateY: constraints.maxHeight * 0.933189937046596,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget46())
                  ]);
                }),
              ),
              Positioned(
                left: -1.0,
                top: 820.0,
                right: null,
                bottom: null,
                width: 429.0,
                height: 124.0,
                child: GeneratedFOOTERWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.0759345897729846;

                  final double height =
                      constraints.maxHeight * 0.037300246102469306;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7827102734846769,
                        y: constraints.maxHeight * 0.9287257194519043,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06474300513520909;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      26.803604125976562;

                  double percentHeight = 0.03131750651768276;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      28.06048583984375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.13785099637681159,
                        translateY: constraints.maxHeight * 0.9375095367431641,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget49())
                  ]);
                }),
              ),
              Positioned(
                left: 148.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 115.5,
                child: GeneratedDoctorcheckedplant178609341Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 147.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 116.98905944824219,
                child: GeneratedScreenShot20170525at3481Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 642.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 116.98905944824219,
                child: GeneratedScreenShot20170525at3482Widget(),
              )
            ]),
      ),
    ));
  }
}
