import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedEllipse138Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedBicamerafillWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedProfileWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedRectangle2873Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedYourNameWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedRectangle2871Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedPincodeWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedModi2Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedPlaceWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedAcresoflandWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedRectangle2870Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedRectangle2872Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax35widget/generated/GeneratedEvaarrowbackfillWidget10.dart';

/* Frame iPhone 11 Pro Max - 35
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax35Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: 106.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 39.0,
                child: GeneratedProfileWidget1(),
              ),
              Positioned(
                left: 39.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget10(),
              ),
              Positioned(
                left: 153.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 110.0,
                child: GeneratedEllipse138Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 26.0,
                child: GeneratedYourNameWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 26.0,
                child: GeneratedPincodeWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 29.0,
                child: GeneratedPlaceWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 26.0,
                child: GeneratedAcresoflandWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedRectangle2870Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedRectangle2871Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedRectangle2872Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedRectangle2873Widget(),
              ),
              Positioned(
                left: 247.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 93.0,
                child: GeneratedModi2Widget1(),
              ),
              Positioned(
                left: 231.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedBicamerafillWidget(),
              )
            ]),
      ),
    ));
  }
}
