import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedRectangle2884Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedAkariconsminusWidget8.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedLine9Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedAkariconsplusWidget5.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedEvaarrowbackfillWidget12.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedTotal2itemsWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedVectorWidget106.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/Generated1Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedAkariconsminusWidget7.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedRectangle2887Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/Generated1Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedRectangle2888Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedVectorWidget105.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedRectangle2886Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedCutivator1Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/Generated\$150Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedRectangle2891Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedCultivatorWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedRectangle2890Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/Generated\$300Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedAkariconscircleminusfillWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedSpray1Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedRectangle2913Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedWatchlistWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/Generated4StrokeSprayerPumpWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax58widget/generated/GeneratedAkariconscircleminusfillWidget4.dart';

/* Frame iPhone 11 Pro Max - 58
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax58Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: -8.0,
                top: -35.0,
                right: null,
                bottom: null,
                width: 443.0,
                height: 206.0,
                child: GeneratedRectangle2913Widget2(),
              ),
              Positioned(
                left: 106.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 39.0,
                child: GeneratedWatchlistWidget1(),
              ),
              Positioned(
                left: 39.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget12(),
              ),
              Positioned(
                left: 52.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 28.0,
                child: GeneratedTotal2itemsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 1.0,
                child: GeneratedLine9Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 136.0,
                child: GeneratedRectangle2884Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 136.0,
                child: GeneratedRectangle2888Widget1(),
              ),
              Positioned(
                left: 151.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 206.0,
                height: 28.0,
                child: Generated4StrokeSprayerPumpWidget1(),
              ),
              Positioned(
                left: 158.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 31.0,
                child: GeneratedCultivatorWidget1(),
              ),
              Positioned(
                left: 300.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 37.0,
                child: GeneratedRectangle2886Widget2(),
              ),
              Positioned(
                left: 300.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 37.0,
                child: GeneratedRectangle2890Widget1(),
              ),
              Positioned(
                left: 315.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 27.0,
                child: Generated$300Widget1(),
              ),
              Positioned(
                left: 315.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 27.0,
                child: Generated$150Widget1(),
              ),
              Positioned(
                left: 172.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 37.0,
                child: GeneratedRectangle2887Widget1(),
              ),
              Positioned(
                left: 172.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 37.0,
                child: GeneratedRectangle2891Widget1(),
              ),
              Positioned(
                left: 224.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 27.0,
                child: Generated1Widget2(),
              ),
              Positioned(
                left: 224.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 27.0,
                child: Generated1Widget3(),
              ),
              Positioned(
                left: 373.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedAkariconsplusWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.024922172804385568;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      10.317779541015625;

                  double percentHeight = 0.011519057410103934;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      10.321075439453125;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6004672580295138,
                        translateY: constraints.maxHeight * 0.3250539984021868,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget105())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.024922172804385568;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      10.317779541015625;

                  double percentHeight = 0.011519057410103934;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      10.321075439453125;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6004672580295138,
                        translateY: constraints.maxHeight * 0.5269978387015206,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget106())
                  ]);
                }),
              ),
              Positioned(
                left: 191.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 24.0,
                child: GeneratedAkariconsminusWidget7(),
              ),
              Positioned(
                left: 191.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 24.0,
                child: GeneratedAkariconsminusWidget8(),
              ),
              Positioned(
                left: 47.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 105.0,
                child: GeneratedSpray1Widget1(),
              ),
              Positioned(
                left: 59.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 94.55999755859375,
                height: 79.33589935302734,
                child: GeneratedCutivator1Widget1(),
              ),
              Positioned(
                left: 358.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedAkariconscircleminusfillWidget3(),
              ),
              Positioned(
                left: 358.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedAkariconscircleminusfillWidget4(),
              )
            ]),
      ),
    ));
  }
}
