import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedTransportdutycutfrompriceWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedSellathomeaddressWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedGoodWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedComponent12Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedEllipse130Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedMapWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedQualityWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedProcesstoSellWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedEllipse134Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedEllipse132Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedSellatgivenlocationWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedEllipse133Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedEvaarrowbackfillWidget5.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/Generated32pptWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedFertilisersUsedWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedAverageWidget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedAddressWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedEllipse135Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedEllipse128Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/Generated32pptWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedAddressWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax49widget/generated/GeneratedEllipse131Widget1.dart';

/* Frame iPhone 11 Pro Max - 49
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax49Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 53.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 38.0,
                child: GeneratedProcesstoSellWidget1(),
              ),
              Positioned(
                left: 53.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 40.0,
                child: GeneratedQualityWidget1(),
              ),
              Positioned(
                left: 99.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 29.0,
                child: GeneratedGoodWidget1(),
              ),
              Positioned(
                left: 192.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 29.0,
                child: GeneratedMapWidget1(),
              ),
              Positioned(
                left: 97.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: Generated32pptWidget2(),
              ),
              Positioned(
                left: 98.0,
                top: 387.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: Generated32pptWidget3(),
              ),
              Positioned(
                left: 53.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 37.0,
                child: GeneratedFertilisersUsedWidget1(),
              ),
              Positioned(
                left: 96.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 29.0,
                child: GeneratedAverageWidget1(),
              ),
              Positioned(
                left: 59.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse128Widget1(),
              ),
              Positioned(
                left: 59.0,
                top: 387.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse132Widget1(),
              ),
              Positioned(
                left: 59.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse133Widget1(),
              ),
              Positioned(
                left: 59.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse134Widget1(),
              ),
              Positioned(
                left: 59.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse130Widget1(),
              ),
              Positioned(
                left: 59.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse131Widget1(),
              ),
              Positioned(
                left: 104.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 32.0,
                child: GeneratedSellatgivenlocationWidget1(),
              ),
              Positioned(
                left: 45.0,
                top: 666.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 29.0,
                child: GeneratedAddressWidget2(),
              ),
              Positioned(
                left: 44.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 29.0,
                child: GeneratedAddressWidget3(),
              ),
              Positioned(
                left: 103.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 32.0,
                child: GeneratedSellathomeaddressWidget1(),
              ),
              Positioned(
                left: 158.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 22.0,
                child: GeneratedComponent12Widget1(),
              ),
              Positioned(
                left: 139.0,
                top: 630.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 23.0,
                child: GeneratedTransportdutycutfrompriceWidget1(),
              ),
              Positioned(
                left: 93.0,
                top: 702.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 90.0,
                child:
                    GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram1(),
              ),
              Positioned(
                left: 64.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedEllipse135Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget5(),
              )
            ]),
      ),
    ));
  }
}
