import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax31widget/generated/GeneratedFrame285Widget.dart';

/* Frame iPhone 13 Pro Max - 31
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax31Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1523.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 243, 243, 243),
                              ),
                            ),
                            Positioned(
                              left: -7.0,
                              top: 61.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1462.0,
                              child: GeneratedFrame285Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
