import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax33widget/generated/GeneratedContinueWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax33widget/generated/GeneratedFrame268Widget6.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax33widget/generated/GeneratedFrame268Widget7.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax33widget/generated/GeneratedGetitbyWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax33widget/generated/GeneratedFrame272Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax33widget/generated/GeneratedContinueWidget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax33widget/generated/GeneratedFrame281Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax33widget/generated/GeneratedDelivertoWidget3.dart';

/* Frame iPhone 13 Pro Max - 33
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax33Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: 21.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 137.0,
                child: GeneratedFrame268Widget6(),
              ),
              Positioned(
                left: 42.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 48.0,
                child: GeneratedDelivertoWidget3(),
              ),
              Positioned(
                left: 14.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 447.0,
                child: GeneratedFrame268Widget7(),
              ),
              Positioned(
                left: 22.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 48.0,
                child: GeneratedGetitbyWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2854417441547781;

                  final double height =
                      constraints.maxHeight * 0.030790397099086216;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.35933902758907005,
                        y: constraints.maxHeight * 0.6099440029689244,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedContinueWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 32.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 104.0,
                child: GeneratedFrame281Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 782.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 67.0,
                child: GeneratedFrame272Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3743961352657005;

                  final double height =
                      constraints.maxHeight * 0.020089285714285716;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.36231884057971014,
                        y: constraints.maxHeight * 0.8872767857142857,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedContinueWidget5(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
