import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedEllipse132Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedProcesstoSellWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedEllipse128Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedSellathomeaddressWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedEvaarrowbackfillWidget6.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedEllipse130Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/Generated32pptWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/Generated32pptWidget5.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedMapWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedFertilisersUsedWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedEllipse136Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedQualityWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedEllipse134Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedEllipse133Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedEllipse131Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedAverageWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedGoodWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedComponent12Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedSellatgivenlocationWidget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedAddressWidget5.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedEllipse135Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedAddressWidget4.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax50widget/generated/GeneratedTransportdutycutfrompriceWidget2.dart';

/* Frame iPhone 11 Pro Max - 50
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax50Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 43.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 47.0,
                child: GeneratedProcesstoSellWidget2(),
              ),
              Positioned(
                left: 51.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 33.0,
                child: GeneratedQualityWidget2(),
              ),
              Positioned(
                left: 97.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 29.0,
                child: GeneratedGoodWidget2(),
              ),
              Positioned(
                left: 190.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 29.0,
                child: GeneratedMapWidget2(),
              ),
              Positioned(
                left: 95.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: Generated32pptWidget4(),
              ),
              Positioned(
                left: 96.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: Generated32pptWidget5(),
              ),
              Positioned(
                left: 51.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 30.0,
                child: GeneratedFertilisersUsedWidget2(),
              ),
              Positioned(
                left: 94.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 29.0,
                child: GeneratedAverageWidget2(),
              ),
              Positioned(
                left: 57.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse128Widget2(),
              ),
              Positioned(
                left: 57.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse132Widget2(),
              ),
              Positioned(
                left: 57.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse133Widget2(),
              ),
              Positioned(
                left: 57.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse134Widget2(),
              ),
              Positioned(
                left: 57.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse130Widget2(),
              ),
              Positioned(
                left: 57.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse131Widget2(),
              ),
              Positioned(
                left: 102.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 32.0,
                child: GeneratedSellatgivenlocationWidget2(),
              ),
              Positioned(
                left: 43.0,
                top: 676.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 29.0,
                child: GeneratedAddressWidget4(),
              ),
              Positioned(
                left: 42.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 29.0,
                child: GeneratedAddressWidget5(),
              ),
              Positioned(
                left: 101.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 32.0,
                child: GeneratedSellathomeaddressWidget2(),
              ),
              Positioned(
                left: 156.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 22.0,
                child: GeneratedComponent12Widget2(),
              ),
              Positioned(
                left: 137.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 23.0,
                child: GeneratedTransportdutycutfrompriceWidget2(),
              ),
              Positioned(
                left: 91.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 90.0,
                child:
                    GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram2(),
              ),
              Positioned(
                left: 62.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedEllipse135Widget1(),
              ),
              Positioned(
                left: 62.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedEllipse136Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget6(),
              )
            ]),
      ),
    ));
  }
}
