import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/GeneratedEvaarrowbackfillWidget19.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/GeneratedNumberboxWidget5.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/GeneratedOTPWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/GeneratedRectangle120Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/GeneratedVerificationcodeWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/GeneratedWehavesentcodeverificationtoyourmobilenumberWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/GeneratedSubmitWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/GeneratedJamwritefWidget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/GeneratedRectangle117Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/GeneratedRectangle119Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/GeneratedEnterOTPpana1Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/GeneratedRectangle118Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone13promax8widget/generated/Generated9422034213Widget1.dart';

/* Frame iPhone 13 Pro Max - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: null,
                top: 743.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 57.0,
                child: TransformHelper.translate(
                    x: 3.00, y: 0.00, z: 0, child: GeneratedNumberboxWidget5()),
              ),
              Positioned(
                left: 115.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 24.0,
                child: GeneratedVerificationcodeWidget(),
              ),
              Positioned(
                left: 173.0,
                top: 753.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 26.0,
                child: GeneratedSubmitWidget(),
              ),
              Positioned(
                left: 190.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 26.0,
                child: GeneratedOTPWidget(),
              ),
              Positioned(
                left: 44.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEvaarrowbackfillWidget19(),
              ),
              Positioned(
                left: 54.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 48.0,
                child:
                    GeneratedWehavesentcodeverificationtoyourmobilenumberWidget(),
              ),
              Positioned(
                left: 146.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 26.0,
                child: Generated9422034213Widget1(),
              ),
              Positioned(
                left: 271.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 18.0,
                child: GeneratedJamwritefWidget(),
              ),
              Positioned(
                left: 68.0,
                top: 663.4697265625,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedRectangle117Widget(),
              ),
              Positioned(
                left: 150.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedRectangle118Widget(),
              ),
              Positioned(
                left: 227.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedRectangle119Widget(),
              ),
              Positioned(
                left: 308.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedRectangle120Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 255.0,
                child: GeneratedEnterOTPpana1Widget(),
              )
            ]),
      ),
    ));
  }
}
