import 'package:flutter/material.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedSellatgivenlocationWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/Generated32pptWidget6.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedProcesstoSellWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedSellathomeaddressWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedEllipse130Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedAddressWidget7.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedEllipse136Widget1.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedEllipse134Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedFertilisersUsedWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedEllipse137Widget.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedEllipse131Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedEllipse132Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedTransportdutycutfrompriceWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedQualityWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedEllipse128Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedAverageWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedComponent12Widget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedEllipse135Widget2.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedGoodWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedAddressWidget6.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedMapWidget3.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedEvaarrowbackfillWidget7.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/Generated32pptWidget7.dart';
import 'package:flutterapp/agrofastapp/generatediphone11promax51widget/generated/GeneratedEllipse133Widget3.dart';

/* Frame iPhone 11 Pro Max - 51
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax51Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 43.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 47.0,
                child: GeneratedProcesstoSellWidget3(),
              ),
              Positioned(
                left: 54.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 33.0,
                child: GeneratedQualityWidget3(),
              ),
              Positioned(
                left: 100.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 29.0,
                child: GeneratedGoodWidget3(),
              ),
              Positioned(
                left: 193.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 29.0,
                child: GeneratedMapWidget3(),
              ),
              Positioned(
                left: 98.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: Generated32pptWidget6(),
              ),
              Positioned(
                left: 99.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: Generated32pptWidget7(),
              ),
              Positioned(
                left: 54.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 30.0,
                child: GeneratedFertilisersUsedWidget3(),
              ),
              Positioned(
                left: 97.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 29.0,
                child: GeneratedAverageWidget3(),
              ),
              Positioned(
                left: 60.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse128Widget3(),
              ),
              Positioned(
                left: 60.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse132Widget3(),
              ),
              Positioned(
                left: 60.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse133Widget3(),
              ),
              Positioned(
                left: 60.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse134Widget3(),
              ),
              Positioned(
                left: 60.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse130Widget3(),
              ),
              Positioned(
                left: 60.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEllipse131Widget3(),
              ),
              Positioned(
                left: 105.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 32.0,
                child: GeneratedSellatgivenlocationWidget3(),
              ),
              Positioned(
                left: 46.0,
                top: 676.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 29.0,
                child: GeneratedAddressWidget6(),
              ),
              Positioned(
                left: 45.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 29.0,
                child: GeneratedAddressWidget7(),
              ),
              Positioned(
                left: 104.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 32.0,
                child: GeneratedSellathomeaddressWidget3(),
              ),
              Positioned(
                left: 159.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 22.0,
                child: GeneratedComponent12Widget3(),
              ),
              Positioned(
                left: 140.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 23.0,
                child: GeneratedTransportdutycutfrompriceWidget3(),
              ),
              Positioned(
                left: 94.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 90.0,
                child:
                    GeneratedSrinivasaNilayamramalayamroadVelagaleru521456Myalavaram3(),
              ),
              Positioned(
                left: 65.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedEllipse135Widget2(),
              ),
              Positioned(
                left: 65.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedEllipse136Widget1(),
              ),
              Positioned(
                left: 65.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedEllipse137Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedEvaarrowbackfillWidget7(),
              )
            ]),
      ),
    ));
  }
}
